name: tws-portfolio

on:
    push:
        branches:
            - main

jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: action/checkout@v1
          with:
            aws-access-key-id : ${{secrets.AWS_ACCESS_ID}}
