name: tws-portfolio

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: action/checkout@v1

            - name: Configure AWS Credientials
              uses: aws-action/configure-aws-credientials@v1
              with:
                  aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
                  aws-access-key: ${{secrets.AWS_SECRET_ACESS_KEY}}
                  aws-region: us-east-1

            - name: Depoy Static Site in S3 Bucket
              run: aws s3 sync s3://portfolio-tws --delete
